### ISSUE TITLE
Bug import colleurs csv

### ISSUE THREAD

**Issue by sebreyt** [stephanekirsch/e-colle#61]
Bonjour Stéphane, 
Je rencontre des difficultés à importer des colleurs via un csv. Je ne suis pas sûr du délimiteur à utiliser mais j'ai un peu tout essayé, notamment en me basant sur les exports de e-colle lui-même. J'ai fait les dernières mises à jour et j'ai appliqué les migrations.
Même si je n'ai qu'un csv avec les noms et prénoms, j'ai droit à `"<Colleur: >" needs to have a value for field "id" before this many-to-many relationship can be used.`
Et si j'essaye de rajouter les classes ou les matières, j'ai une erreur serveur (sur 'nomclasse' ou 'nommatiere', c'est selon) : 
```
Environment:


Request Method: POST
Request URL: https://colles.cpge-michelet.fr/administrateur/action/colleur/csv

Django Version: 3.1.1
Python Version: 3.8.10
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'accueil.apps.accueilConfig',
 'administrateur.apps.administrateurConfig',
 'eleve.apps.eleveConfig',
 'colleur.apps.colleurConfig',
 'secretariat.apps.secretariatConfig',
 'app_mobile.apps.appMobileConfig',
 'customfilter.apps.customfilterConfig',
 'ckeditor')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')



Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/var/www/html/e-colle/administrateur/views.py", line 48, in wrapped_view
    return func(request, *args, **kwargs)
  File "/var/www/html/e-colle/administrateur/views.py", line 509, in colleurcsv
    if form.is_valid():
  File "/usr/local/lib/python3.8/dist-packages/django/forms/forms.py", line 177, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.8/dist-packages/django/forms/forms.py", line 172, in errors
    self.full_clean()
  File "/usr/local/lib/python3.8/dist-packages/django/forms/forms.py", line 375, in full_clean
    self._clean_form()
  File "/usr/local/lib/python3.8/dist-packages/django/forms/forms.py", line 402, in _clean_form
    cleaned_data = self.clean()
  File "/var/www/html/e-colle/administrateur/forms.py", line 850, in clean
    donnee = [x.strip().lower() for x in ligne[self.cleaned_data['nomclasse']].split(";")]

Exception Type: KeyError at /administrateur/action/colleur/csv
Exception Value: 'nomclasse'

```
Merci encore pour tout le travail et toutes ces nouvelles fonctionnalités !

**Comment by stephanekirsch** [comment]
Bonjour,
Je corrige ça dans la journée. C'est vrai que j'ai pas trop pris le temps de tester, désolé ... :(

**Comment by stephanekirsch** [comment]
Bon j'ai essayé de corrigéer les erreurs que tu as mentionnées. Il manquait effectivement un 's' dans des clés de dictionnaires, et j'essayais d'attribuer de classes / matières a des colleurs non encore enregistrés en BDD.

**Comment by stephanekirsch** [comment]
Je viens de refaire une modif à l'instant.

**Comment by sebreyt** [comment]
Merci pour ta célérité !
La mise à jour a été "effectuée avec succès", mais avec cette erreur : 

```
Mise à jour de la structure de la base de données
Requirement already satisfied: django in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 1)) (3.1.1)
Requirement already satisfied: pexpect in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (4.6.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 3)) (7.2.0)
Requirement already satisfied: qrcode in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 4)) (6.1)
Requirement already satisfied: reportlab in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 5)) (3.5.49)
Requirement already satisfied: unidecode in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 6)) (1.1.1)
Requirement already satisfied: django-ckeditor in /home/reyt/.local/lib/python3.8/site-packages (from -r requirements.txt (line 7)) (6.1.0)
Requirement already satisfied: sqlparse>=0.2.2 in /usr/local/lib/python3.8/dist-packages (from django->-r requirements.txt (line 1)) (0.3.1)
Requirement already satisfied: asgiref~=3.2.10 in /usr/local/lib/python3.8/dist-packages (from django->-r requirements.txt (line 1)) (3.2.10)
Requirement already satisfied: pytz in /usr/lib/python3/dist-packages (from django->-r requirements.txt (line 1)) (2019.3)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from qrcode->-r requirements.txt (line 4)) (1.14.0)
Requirement already satisfied: django-js-asset>=1.2.2 in /home/reyt/.local/lib/python3.8/site-packages (from django-ckeditor->-r requirements.txt (line 7)) (1.2.2)
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 392, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/reyt/e-colle-new/ecolle/urls.py", line 5, in <module>
    from accueil import views
  File "/home/reyt/e-colle-new/accueil/views.py", line 7, in <module>
    from accueil.forms import UserForm, UserProfprincipalForm, SelectMessageForm, EcrireForm, ReponseForm
  File "/home/reyt/e-colle-new/accueil/forms.py", line 4, in <module>
    from administrateur.forms import CustomMultipleChoiceField
  File "/home/reyt/e-colle-new/administrateur/forms.py", line 925
    user.colleur = colleur
    ^
SyntaxError: invalid syntax
copie des fichiers media/backup
la mise a jour a été effectuée avec succès.

```
Et j'ai maintenant une erreur 500 qui me sort la même chose d'après les log.

**Comment by stephanekirsch** [comment]
j'avais oublié une parenthèse....
c'est corrigé

**Comment by sebreyt** [comment]
Merci. 
J'ai de nouveau accès à e-colle, et l'import fonctionne s'il n'y a que les prénoms et noms, mais si je rajoute classes et matières j'obtiens `Unsupported lookup 'iexact' for CharField or join on the field not permitted, perhaps you meant iexact or exact?`
Ça avance, j'imagine, même si tout ça reste fort obscur pour moi ;)

**Comment by sebreyt** [comment]
Et au passage, je crois que je viens de remarquer que même si on importe que les noms et prénoms, le menu déroulant "classe" de la fenêtre de l'import de présélectionne pas les classes dans la fenêtre d'édition qui vient ensuite. Et idem pour la matière.

**Comment by stephanekirsch** [comment]
normalement c'est tout bon maintenant...

**Comment by stephanekirsch** [comment]
J'en profite pour préciser que les noms de matières dans le csv doivent être complets, c'est-à-dire sous la forme
anglais(Gr/LV1)
physique(Gr)
français/philo(So)
etc...

**Comment by sebreyt** [comment]
Merci pour le correctif, plus d'erreur en effet ! 
En revanche j'ai effectivement du mal à lui faire prendre en compte les matières (avec majuscule ou non, je n'ai aucune matière sélectionnée quand j'arrive à l'étape suivante, tandis que les noms semblent pourtant bien correspondre).
Et j'ai eu aussi un peu de mal pour les classes, mais j'ai fini par réussir à en mettre plusieurs en mettant des , comme délimiteur du fichier principal, et des ; pour délimiter les différentes classes.

**Comment by stephanekirsch** [comment]
Il reste effectivement un dernier soucis avec les matières.
Je vais enquêter!

**Comment by stephanekirsch** [comment]
je pense avoir résolu le problème.

**Comment by sebreyt** [comment]
C'est royal, tout fonctionne, et c'est même pas sensible à la casse, c'est parfait ! 
Merci pour tout et bon dimanche

**Comment by stephanekirsch** [comment]
Merci à toi pour le debuggage 😁
